modLoader="javafml"
loaderVersion="[4,)"
license="Apache License version 2.0"

[[mods]]
modId="mobs_blocker"
<<<<<<< Updated upstream
version="1.0.4"
=======
version="1.0.9"
>>>>>>> Stashed changes
displayName="Mobs Blocker"
displayURL="https://github.com/Dreyka-Oas/MobsBlocker.git"
logoFile="logo.png"
credits="O.A.S"
authors="Dreyka Oas"
description="Mob spawn blocker"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.mobs_blocker]]
    modId="neoforge"
    type="required"
<<<<<<< Updated upstream
    versionRange="[21.1.65,)"
=======
    versionRange="[21.1.92,)"
>>>>>>> Stashed changes
    ordering="AFTER"
    side="BOTH"

[[dependencies.mobs_blocker]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration